// Local two-person walkthrough. No server, identity verification, delivery, or cross-device state.
const QUESTIONS=[
  {topic:'CORE VALUES',q:'A truth might disappoint someone you like. What do you do?',a:['Tell them directly, with care.','Wait for a better moment.','Keep it to myself unless they ask.']},
  {topic:'COMMUNICATION',q:'Something they said bothers you. How do you start the conversation?',a:['Tell them what I heard and ask what they meant.','Give myself time, then bring it up.','Wait to see if it happens again.']},
  {topic:'REPAIR',q:'You still think you were right after an argument. What happens next?',a:['Ask how it felt from their side.','Own what I could have done differently.','Give us space and let it pass.']},
  {topic:'BOUNDARIES',q:'Someone you like asks for a little space. What do you say?',a:['“Of course. When should we check in?”','“Okay, I’ll let you reach out.”','“I need to understand why first.”']},
  {topic:'ACCOUNTABILITY',q:'You forget something that mattered to them. What do you say first?',a:['“I forgot. I’m sorry. Tell me how it affected you.”','“I didn’t mean to hurt you.”','“I’ve had a lot going on.”']},
  {topic:'EMOTIONAL EXPRESSION',q:'You’ve had a rough day. How do you let someone close to you know?',a:['“I could use some company.”','“I need a little time, then let’s talk.”','I tend to keep it to myself.']},
  {topic:'CLOSENESS',q:'You’re beginning to care about someone. What feels most important?',a:['Feeling safe enough to be honest.','Keeping room for our own lives.','Seeing steady actions, not just words.']},
  {topic:'RESPONSIVENESS',q:'They text while you’re swamped. What do you usually do?',a:['Send a quick “busy, talk soon.”','Wait until I can give a real answer.','Reply when my day is done.']},
  {topic:'NON-NEGOTIABLES',q:'They want something from a relationship that you don’t. What comes first?',a:['Ask why it matters to them.','Explain my own limit clearly.','Take time to decide whether we fit.']},
  {topic:'KEEPING AGREEMENTS',q:'You made plans, then something better comes up. What do you do?',a:['Keep our plans.','Ask if changing plans would be okay.','Suggest another time.']}
];
const TESTS=[['Love Language','How you show and receive affection','love-language'],['Attachment','How you respond to closeness and distance','attachment'],['Communication Style','How you start and repair conversations','communication-style'],['Emotional Expression','How you share feelings','emotional-expression'],['Personality','Patterns that shape how you relate','personality']];
const KEY='chempatibility.walkthrough.v3';
// A new key starts everyone with a clean walkthrough after this deployment.
try{sessionStorage.removeItem('chempatibility.walkthrough.v2')}catch{}
const blank=()=>({view:'landing',actor:'member',member:{name:'',contact:'',photo:'',answers:[]},prospect:{name:'',phone:'',email:'',photo:'',answers:[]},phase:'registration',index:0,pick:null,modal:'',messages:[],notice:'',testRequest:''});
let s;try{s={...blank(),...JSON.parse(sessionStorage.getItem(KEY)||'{}')}}catch{s=blank()}
if(!['landing','dashboard','questions','invitee','results','request','conversation','email','tests'].includes(s.view))s.view='landing';
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const first=x=>(x||'Friend').trim().split(/\s+/)[0];
const name=a=>first(a==='member'?s.member.name:s.prospect.name);
const photo=a=>a==='member'?s.member.photo:s.prospect.photo;
const face=(a,size='')=>`<span class="face ${size}">${photo(a)?`<img src="${photo(a)}" alt="${esc(name(a))}">`:esc(name(a)[0])}</span>`;
const button=(label,action,style='')=>`<button type="button" class="button ${style}" onclick="${action}">${label}</button>`;
const save=()=>{try{sessionStorage.setItem(KEY,JSON.stringify(s))}catch{ /* Camera images may exceed browser storage; this tab still works. */ }};
const mask=phone=>phone?`••• ••• ${phone.replace(/\D/g,'').slice(-4)}`:'Phone pending';
const steps=()=>`<div aria-label="Game stages"><span class="miniStep">1 · My ten</span><span class="miniStep">2 · Their first five</span><span class="miniStep">3 · Reveal &amp; request</span><span class="miniStep">4 · Chat &amp; next five</span></div>`;
function render(){save();let actor=s.actor; $('navUser').innerHTML=s.view==='landing'?'':`<div class="user">${face(actor)}<span><b>${esc(name(actor))}</b><small>${actor==='member'?'My page':'Prospect view'}</small></span></div>`;
let html='';
if(s.view==='landing')html=`<div class="hero"><div class="eyebrow">CHEMPATIBILITY</div><h1>Chem-<em>patibility</em>: IYKYK!</h1><p>Chemistry and compatibility make for the memories.</p></div><div class="grid"><section class="box"><h2>Three steps. You’re in.</h2><p>A name, a way to reach you, and a smile.</p><label class="field">Your name<input id="joinName" autocomplete="given-name" maxlength="50" placeholder="First name" value="${esc(s.member.name)}"></label><label class="field">Email or cell<input id="joinContact" autocomplete="email" placeholder="you@example.com or your cell" value="${esc(s.member.contact)}"></label><div class="hint">1 · Your details &nbsp; 2 · Your picture &nbsp; 3 · Your page</div><label class="field">CHOOSE YOUR PICTURE<input type="file" accept="image/*" onchange="uploadPhoto(event,'member')"></label><div class="cameraActions"><button type="button" class="button alt" onclick="openCamera()">OPEN CAMERA</button><button id="captureBtn" type="button" class="button light" onclick="captureCamera()" hidden>SMILE & CAPTURE</button></div><button id="finishBtn" type="button" class="button" onclick="finishRegistration()" ${s.member.photo?'':'disabled'}>FINISH →</button><p id="joinError" class="error" role="alert"></p></section><section class="box"><h2>Smile. This is you.</h2><p>Choose your picture. Give them a face to meet.</p><div class="selfieFrame" id="selfieFrame">${s.member.photo?`<img src="${s.member.photo}" alt="Captured selfie">`:'<span class="smile">☺</span><b>Your picture goes here</b><small>A current photo, taken now</small>'}</div><video id="cameraPreview" class="selfieFrame" autoplay muted playsinline hidden></video><canvas id="cameraCanvas" hidden></canvas><p class="hint">Your picture appears here. It stays in this browser tab.</p></section></div><div class="hero"><div class="eyebrow">A LOOK INSIDE</div><h2>Your page is where a connection begins.</h2><p>Answer ten quick situations. Then invite someone to play your first five.</p></div>${steps()}`;
if(s.view==='dashboard'){let ready=s.member.answers.length===10;html=`<div class="hero"><div class="eyebrow">MY PAGE</div><h1>Hi, ${esc(name('member'))}.</h1><p>Meet someone interesting? Give them a way to know you.</p></div>${s.phase==='firstResults'?`<div class="notice"><b>Your first five just opened.</b> Someone played, and your answers are ready to compare. <button class="link" onclick="navigate('results','member')">SEE OUR ANSWERS →</button></div>`:''}${!ready?`<div class="introCard"><div class="eyebrow">FIRST, YOUR TEN</div><h2>The best conversations start with your answers.</h2><p>Ten quick situations. Choose what you’d really do. Your first five stay hidden until the other person plays.</p>${button(s.member.answers.length?'CONTINUE MY TEN →':'LET’S PLAY MY TEN →','startMemberQuestions()')}</div>`:`<div class="banner"><div class="eyebrow" style="color:#ffc5ad">READY TO CONNECT</div><h2>Your ten are in. Now let someone in on your first five.</h2><p>They answer five, you both see the choices, and a connection request can follow.</p>${button('CONNECT NOW →','openInvite()')}</div>`}<div class="grid"><div class="stack"><section class="box"><h2>My invitation</h2><p>${ready?'Show your code to someone you met. The visitor gets your photo, first name, and Five to Vibe.':'Answer your ten to unlock the invitation.'}</p>${ready?`<div class="row">${button('OPEN INVITATION →','openInvite()','alt')}${button('SIMULATE A SCAN →','simulateScan()','light')}</div>`:''}</section><section class="box"><h2>My 10</h2><p>These same questions become the visitor’s first five and next five.</p><ol class="list">${QUESTIONS.map((q,i)=>`<li>${esc(q.q)} <span class="small">${s.member.answers[i]!==undefined?'✓':''}</span></li>`).join('')}</ol></section></div><section class="box"><h2>Chempats</h2>${s.prospect.answers.length?`<button class="connection" onclick="showConnection()">${face('prospect')}<span><b>${esc(name('prospect'))}</b><br><small>${esc(connectionStatus())}</small></span><span>→</span></button>`:'<p>Your invitations and conversations appear here.</p>'}${s.phase==='request'?`<div class="notice"><b>${esc(name('prospect'))} wants to connect.</b><p>Phone ${esc(mask(s.prospect.phone))}. Choose whether to open your chat.</p><div class="row">${button('ACCEPT & OPEN CHAT →','acceptRequest()')}${button('PASS','declineRequest()','light')}</div></div>`:''}${s.phase==='chat'||s.phase==='secondFive'||s.phase==='email'||s.phase==='tests'?`<div class="row">${button('OPEN OUR SPACE →','openConversation()','alt')}</div>`:''}</section></div>`}
if(s.view==='questions'){let member=s.actor==='member',offset=member?0:(s.phase==='secondFive'?5:0),count=member?10:5,answers=member?s.member.answers:s.prospect.answers,index=answers.length-offset,q=QUESTIONS[offset+index];if(index>=count){s.view=member?'dashboard':'results';return render()}html=`<div class="hero"><div class="eyebrow">${member?'MAKE YOUR PAGE':'FIVE TO VIBE'} · ${index+1} OF ${count}</div><h1>${member?'Your answers make the introduction.':'Pick what you’d actually do.'}</h1><p>${member?'The first five are revealed only after someone plays.':'Your answers and theirs will reveal together.'}</p></div><div class="progress">${Array.from({length:count},(_,i)=>`<span class="${i<=index?'done':''}"></span>`).join('')}</div><div class="grid"><section class="question"><div class="eyebrow">${esc(q.topic)}</div><h2>${esc(q.q)}</h2>${q.a.map((a,i)=>`<button type="button" class="option ${s.pick===i?'on':''}" aria-pressed="${s.pick===i}" onclick="pick(${i})">${'ABC'[i]}. ${esc(a)}</button>`).join('')}<div class="row">${button(index===count-1?(member?'FINISH MY TEN →':offset?'REVEAL OUR NEXT FIVE →':'REVEAL OUR FIRST FIVE →'):'NEXT →','answerQuestion()')}</div><p id="answerError" class="error" role="alert"></p></section><aside class="box"><h3>${member?'The game begins with you.':`${esc(name('member'))} answered already.`}</h3><p>${member?'Answer all ten, then show your invitation. You can see your choices again on your page.':'Pick your own answer. Both sets reveal when you finish these five.'}</p></aside></div>`}
if(s.view==='invitee')html=`<div class="hero"><div class="eyebrow">${esc(name('member'))} INVITED YOU</div><h1>Five to Vibe.</h1><p>We already caught a vibe. Answer five quickies, see how we both answered, and let’s keep talking.</p></div><section class="box" style="max-width:600px"><div class="profile">${face('member')}<div><h2>${esc(name('member'))}</h2><p>“I’ve got five answers waiting. Wanna play?”</p></div></div><div class="row">${button('PLAY MY FIVE →','startProspect()')}</div><p class="hint">Five quick situations. Your answers reveal together.</p></section>`;
if(s.view==='results'){let offset=s.phase==='secondResults'||s.phase==='email'||s.phase==='tests'?5:0;html=`<div class="hero"><div class="eyebrow">${offset?'THE NEXT FIVE':'FIRST FIVE'} · BOTH SIDES</div><h1>Now you’ve got something to talk about.</h1><p>Read each other’s answers. There’s no score.</p></div><div class="box">${QUESTIONS.slice(offset,offset+5).map((q,i)=>`<div class="reveal"><div class="eyebrow">${esc(q.topic)}</div><h3>${esc(q.q)}</h3><div class="pair"><div><div class="answerIdentity">${face('member')}<b>${esc(name('member'))}</b></div>${esc(q.a[s.member.answers[offset+i]]||'Waiting')}</div><div><div class="answerIdentity">${face('prospect')}<b>${esc(name('prospect'))}</b></div>${esc(q.a[s.prospect.answers[offset+i]]||'Waiting')}</div></div></div>`).join('')}<div class="row">${offset?button('CONTINUE →','continueAfterSecond()'):s.actor==='prospect'?button('I’D LIKE TO CONNECT →','showRequest()'):button('MY PAGE →','goHome()','alt')}</div></div>`}
if(s.view==='request')html=`<div class="hero"><div class="eyebrow">KEEP THE CONVERSATION GOING</div><h1>Want to connect with ${esc(name('member'))}?</h1><p>Choose your picture and send a request. They decide whether to open a private chat.</p></div><div class="box" style="max-width:530px"><label class="field">Your first name<input id="prospectName" autocomplete="given-name" maxlength="50" value="${esc(s.prospect.name)}" placeholder="First name"></label><label class="field">Your picture<input type="file" accept="image/*" onchange="uploadPhoto(event,'prospect')"></label><div class="profile">${face('prospect')}<span class="small">${s.prospect.photo?'Picture ready':'Your picture appears with your request and chat.'}</span></div><label class="field">Your cell<input id="prospectPhone" type="tel" autocomplete="tel" inputmode="tel" value="${esc(s.prospect.phone)}" placeholder="(555) 555-0123"></label><p class="small">Your phone will be masked in the request. Verification and actual delivery are not available in this demo.</p><div class="row">${button('SEND CONNECTION REQUEST →','sendRequest()')}</div><p class="error" id="requestError" role="alert"></p></div>`;
if(s.view==='conversation'){let nextReady=s.prospect.answers.length===10;html=`<div class="hero"><div class="eyebrow">OUR SPACE · ${esc(name('member'))} + ${esc(name('prospect'))}</div><h1>We’re talking.</h1><div class="peopleBar">${face('member')}<b>${esc(name('member'))}</b><span>+</span>${face('prospect')}<b>${esc(name('prospect'))}</b></div><p>You both saw the first five. Keep the conversation going.</p></div><div class="grid"><section class="box"><h2>Chat</h2><div class="chat">${s.messages.length?s.messages.map(m=>`<div class="chatLine ${m.by===s.actor?'mine':''}">${face(m.by)}<p><b>${esc(name(m.by))}</b><br>${esc(m.text)}</p></div>`).join(''):'<p>Say hello. The first five gave you something to start with.</p>'}</div><label class="field">Message as ${esc(name(s.actor))}<input id="message" maxlength="500" placeholder="Say something…" onkeydown="if(event.key==='Enter')sendMessage()"></label><div class="row">${button('SEND →','sendMessage()','alt')}</div></section><aside class="stack"><div class="box"><h3>Five more to unlock email and more.</h3><p>${nextReady?'Both sets of answers are ready to see.':s.actor==='prospect'?'Keep playing to reveal more.':'The next five are ready for them when they come back.'}</p><div class="row">${nextReady?button('SEE OUR NEXT FIVE →','showSecondResults()'):s.actor==='prospect'?button('PLAY THE NEXT FIVE →','startSecondFive()'):''}</div></div><div class="box"><h3>Connection</h3><p>${esc(name('prospect'))} · ${esc(mask(s.prospect.phone))}</p><p class="small">Email comes after the next five.</p></div></aside></div>`}
if(s.view==='email')html=`<div class="hero"><div class="eyebrow">TEN ANSWERS IN</div><h1>Keep this connection close.</h1><p>Five to Vibe gave you a start. There’s more to discover together.</p></div><section class="box" style="max-width:530px"><h2>Your email and more.</h2><p>Save an email for the next chapter of your conversation.</p>${s.actor==='prospect'?`<label class="field">Your email<input id="prospectEmail" type="email" autocomplete="email" value="${esc(s.prospect.email)}" placeholder="you@example.com"></label><div class="row">${button('SAVE & SEE WHAT’S NEXT →','saveEmail()')}</div><p id="emailError" class="error" role="alert"></p>`:`<p>${s.prospect.email?'Email provided for this preview.':'Waiting for their email.'}</p>${button('SEE WHAT’S NEXT →','showTests()')}`}</section>`;
if(s.view==='tests')html=`<div class="hero"><div class="eyebrow">GO DEEPER TOGETHER</div><h1>Choose what to explore next.</h1><p>Either person can take a test, then invite the other to take that same test. Results will reveal after both finish.</p></div><div class="grid"><section class="box"><h2>Shared tests</h2>${TESTS.map(t=>`<div class="testCard"><b>${esc(t[0])}</b><p>${esc(t[1])}</p><a href="/admin#questions/test-${t[2]}" target="_blank" rel="noopener">Read the test brief →</a></div>`).join('')}</section><aside class="box"><h3>Coming into the game</h3><p>These links open test briefs. The assessments, invitations, and mutual results screens have not been built yet.</p><div class="row">${button('BACK TO OUR CHAT →','openConversation()','alt')}</div></aside></div>`;
if(s.notice)html=`<div class="notice" role="status">${esc(s.notice)}</div>`+html;
$('root').innerHTML=html;renderModal();}
function navigate(view,actor){s.view=view;if(actor)s.actor=actor;s.pick=null;s.notice='';render();window.scrollTo(0,0)}
function goHome(){navigate(s.member.answers.length?'dashboard':'landing','member')}
let cameraStream=null;
async function openCamera(){
 const error=$('joinError');error.textContent='';
 if(!navigator.mediaDevices?.getUserMedia){error.textContent='Camera access needs HTTPS and a supported phone browser.';return}
 try{
  cameraStream?.getTracks().forEach(t=>t.stop());
  cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});
  const video=$('cameraPreview');video.srcObject=cameraStream;video.hidden=false;$('selfieFrame').hidden=true;$('captureBtn').hidden=false;
  await video.play();
 }catch(e){cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;error.textContent='Allow camera access and try again.'}
}
function captureCamera(){
 const video=$('cameraPreview');if(!video?.videoWidth){$('joinError').textContent='Wait for the camera, then capture your picture.';return}
 const canvas=$('cameraCanvas'),side=Math.min(video.videoWidth,video.videoHeight);canvas.width=canvas.height=320;
 canvas.getContext('2d').drawImage(video,(video.videoWidth-side)/2,(video.videoHeight-side)/2,side,side,0,0,320,320);
 s.member.photo=canvas.toDataURL('image/jpeg',.78);cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;
 video.srcObject=null;video.hidden=true;$('captureBtn').hidden=true;
 $('selfieFrame').innerHTML=`<img src="${s.member.photo}" alt="Your captured picture">`;$('selfieFrame').hidden=false;
 $('finishBtn').disabled=false;finishRegistration();save();
}
async function uploadPhoto(event,actor){
 const file=event.target.files?.[0];if(!file)return;
 const target=actor==='member'?'joinError':'requestError';
 if(!file.type.startsWith('image/')){$(target).textContent='Choose an image file.';return}
 try{
  const data=await new Promise((resolve,reject)=>{
   const img=new Image(),url=URL.createObjectURL(file);
   img.onload=()=>{try{const canvas=document.createElement('canvas');canvas.width=canvas.height=320;const side=Math.min(img.width,img.height);canvas.getContext('2d').drawImage(img,(img.width-side)/2,(img.height-side)/2,side,side,0,0,320,320);resolve(canvas.toDataURL('image/jpeg',.78))}catch(e){reject(e)}finally{URL.revokeObjectURL(url)}};
   img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Could not open this picture.'))};img.src=url;
  });
  if(actor==='member')s.member.photo=data;else s.prospect.photo=data;
  if(actor==='member'){cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;const v=$('cameraPreview');if(v){v.srcObject=null;v.hidden=true}$('captureBtn').hidden=true;$('selfieFrame').hidden=false;$('selfieFrame').innerHTML=`<img src="${data}" alt="Your uploaded picture">`;$(target).textContent='';$('finishBtn').disabled=false;finishRegistration()}
  else{const n=$('prospectName').value,p=$('prospectPhone').value;render();$('prospectName').value=n;$('prospectPhone').value=p}
  save();
 }catch(e){$(target).textContent=e.message||'Could not open this picture.'}
}
function resetWalkthrough(){
 if(!confirm('Clear this walkthrough and start over in this browser tab?'))return;
 cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;
 try{sessionStorage.removeItem(KEY);sessionStorage.removeItem('chempatibility.walkthrough.v2')}catch{}
 s=blank();render();window.scrollTo(0,0);
}
function finishRegistration(){let n=$('joinName').value.trim(),c=$('joinContact').value.trim();if(!n||!c||!s.member.photo){$('joinError').textContent='Enter your name and contact, then choose your picture.';return}s.member.name=n;s.member.contact=c;s.modal='welcome';renderModal();save()}
function enterGame(){s.modal='';navigate('dashboard','member')}
function startMemberQuestions(){navigate('questions','member')}
function pick(i){s.pick=i;document.querySelectorAll('.option').forEach((el,j)=>{el.classList.toggle('on',j===i);el.setAttribute('aria-pressed',j===i)})}
function answerQuestion(){if(s.pick===null){$('answerError').textContent='Pick one answer to continue.';return}let member=s.actor==='member',arr=member?s.member.answers:s.prospect.answers;arr.push(s.pick);s.pick=null;if(member&&arr.length===10){s.phase='ready';navigate('dashboard','member')}else if(!member&&arr.length===5){s.phase='firstResults';navigate('results','prospect')}else if(!member&&arr.length===10){s.phase='secondResults';navigate('results','prospect')}else render()}
function openInvite(){if(s.member.answers.length!==10)return;s.modal='qr';renderModal()}
function closeInvite(e){if(e&&e.target!==e.currentTarget)return;s.modal='';renderModal()}
function inviteMode(m){s.modal=m;renderModal()}
function renderModal(){let host=$('modalHost');if(!s.modal){host.innerHTML='';return}if(s.modal==='welcome'){host.innerHTML=`<div class="modalBackdrop" onclick="closeInvite(event)"><section class="modal welcomeModal" role="dialog" aria-modal="true" aria-labelledby="welcomeTitle"><button class="close" type="button" aria-label="Close" onclick="closeInvite()">×</button><div class="eyebrow">YOU’RE IN</div><div class="welcomeFace">${face('member')}</div><h2 id="welcomeTitle">Looking good, ${esc(name('member'))}.</h2><p>Ten quick choices make this your game. Then you can show someone your first five.</p>${button('ENTER THE GAME →','enterGame()')}<p class="small">Your page is ready for you.</p></section></div>`;return}host.innerHTML=`<div class="modalBackdrop" onclick="closeInvite(event)"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="inviteTitle"><button class="close" type="button" aria-label="Close invitation" onclick="closeInvite()">×</button><div class="eyebrow">YOUR INVITATION</div><h2 id="inviteTitle">${s.modal==='qr'?'Scan the code. I’ll tell you FIVE secrets about me! Wanna play?':'I caught your vibe. Let’s talk.'}</h2>${s.modal==='qr'?`<div class="invitePair"><div>${s.member.photo?`<img class="portrait" src="${s.member.photo}" alt="${esc(name('member'))}">`:face('member')}<b style="display:block;margin-top:8px">${esc(name('member'))}</b></div><div><div class="placeholderQr" aria-label="QR preview; use simulate scan to try this walkthrough"><span>SCAN ME</span></div></div></div><p class="small">Scan preview · the live QR and shared prospect link need accounts and a server.</p><button class="link" type="button" onclick="inviteMode('send')">Can’t scan? Send it instead →</button><div class="demo"><button class="link" type="button" onclick="simulateScan()">Simulate a scan on this device →</button></div>`:`<div class="modalForm"><label class="field">Their name<input id="inviteName" autocomplete="given-name" placeholder="First name"></label><label class="field">Email or cell<input id="inviteContact" placeholder="Email or cell"></label><div class="row">${button('PREPARE INVITATION →','prepareInvite()')}</div><p id="inviteError" class="error" role="alert"></p><button class="link" type="button" onclick="inviteMode('qr')">← Show code instead</button><p class="small">This preview records an invitation locally. It cannot send a text or email.</p></div>`}</section></div>`}
function prepareInvite(){let n=$('inviteName').value.trim(),c=$('inviteContact').value.trim();if(!n||!c){$('inviteError').textContent='Enter their name and contact.';return}s.prospect.name=n;s.modal='';s.notice=`Invitation prepared for ${n}. Delivery is not connected yet. Use Simulate a scan to walk through their view.`;render()}
function simulateScan(){if(s.member.answers.length!==10)return;s.modal='';s.phase='invited';navigate('invitee','prospect')}
function startProspect(){if(s.prospect.answers.length===0)navigate('questions','prospect');else navigate('results','prospect')}
function showRequest(){navigate('request','prospect')}
function sendRequest(){let n=$('prospectName').value.trim(),p=$('prospectPhone').value.trim(),digits=p.replace(/\D/g,'');if(!n||digits.length<10||!s.prospect.photo){$('requestError').textContent='Add your picture, first name and a ten-digit cell number.';return}s.prospect.name=n;s.prospect.phone=p;s.phase='request';s.notice='Request saved. Switch to the member view to accept it.';navigate('dashboard','member');s.notice=`${n} requested a connection. Their cell is masked.`;render()}
function acceptRequest(){if(s.phase!=='request')return;s.phase='chat';navigate('conversation','member')}
function declineRequest(){s.phase='declined';s.notice='You passed on this connection.';render()}
function openConversation(){navigate('conversation',s.actor)}
function showConnection(){if(s.phase==='request')navigate('dashboard','member');else if(s.phase==='firstResults')navigate('results','member');else if(s.phase==='declined')navigate('dashboard','member');else navigate('conversation','member')}
function connectionStatus(){return ({firstResults:'First five revealed',request:'Connection request · Your move',chat:'Chat open · Next five ready',secondFive:'Next five in progress',secondResults:'Next five revealed',email:'Email stage',tests:'Tests next',declined:'Request passed'})[s.phase]||'Invitation open'}
function sendMessage(){let field=$('message'),v=field?.value.trim();if(!v)return;s.messages.push({by:s.actor,text:v});render()}
function startSecondFive(){if(s.phase==='declined')return;s.phase='secondFive';navigate('questions','prospect')}
function showSecondResults(){s.phase='secondResults';navigate('results',s.actor)}
function continueAfterSecond(){s.phase='email';navigate('email',s.actor)}
function saveEmail(){let v=$('prospectEmail').value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)){$('emailError').textContent='Enter a valid email address.';return}s.prospect.email=v;showTests()}
function showTests(){s.phase='tests';navigate('tests',s.actor)}
function switchView(){if(s.actor==='member'){if(s.phase==='ready'||s.phase==='invited')simulateScan();else if(s.phase==='request')navigate('request','prospect');else if(s.phase==='firstResults')navigate('results','prospect');else if(s.phase==='secondFive')navigate('questions','prospect');else if(s.phase==='secondResults')navigate('results','prospect');else if(s.phase==='email')navigate('email','prospect');else navigate('conversation','prospect')}else{if(s.phase==='request')navigate('dashboard','member');else if(s.phase==='firstResults')navigate('results','member');else if(s.phase==='secondResults')navigate('results','member');else if(s.phase==='ready')navigate('dashboard','member');else navigate('conversation','member')}}
function demoNav(){let current=$('navUser');if(s.view!=='landing'&&s.member.answers.length===10)current.insertAdjacentHTML('beforeend',`<button class="link" type="button" onclick="switchView()">View as ${s.actor==='member'?esc(name('prospect')):esc(name('member'))}</button>`);current.insertAdjacentHTML('beforeend','<button class="link resetLink" type="button" onclick="resetWalkthrough()">RESET</button>')}
const originalRender=render;render=function(){originalRender();demoNav()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&s.modal)closeInvite()});
render();
