// Local game walkthrough with a verified email invitation entry point.
const QUESTIONS=[
  {topic:'CORE VALUES',q:'A truth might disappoint someone you like. What do you do?',a:['Tell them directly, with care.','Wait for a better moment.','Keep it to myself unless they ask.']},
  {topic:'COMMUNICATION',q:'Something they said bothers you. How do you start the conversation?',a:['Tell them what I heard and ask what they meant.','Give myself time, then bring it up.','Wait to see if it happens again.']},
  {topic:'REPAIR',q:'You still think you were right after an argument. What happens next?',a:['Ask how it felt from their side.','Own what I could have done differently.','Give us space and let it pass.']},
  {topic:'BOUNDARIES',q:'Someone you like asks for a little space. What do you say?',a:['“Of course. When should we check in?”','“Okay, I’ll let you reach out.”','“I need to understand why first.”']},
  {topic:'ACCOUNTABILITY',q:'You forget something that mattered to them. What do you say first?',a:['“I forgot. I’m sorry. Tell me how it affected you.”','“I didn’t mean to hurt you.”','“I’ve had a lot going on.”']},
  {topic:'EMOTIONAL EXPRESSION',q:'You’ve had a rough day. How do you let someone close to you know?',a:['“I could use some company.”','“I need a little time, then let’s talk.”','I tend to keep it to myself.']},
  {topic:'CLOSENESS',q:'You’re beginning to care about someone. What feels most important?',a:['Feeling safe enough to be honest.','Keeping room for our own lives.','Seeing steady actions, not just words.']},
  {topic:'RESPONSIVENESS',q:'They text while you’re swamped. What do you usually do?',a:['Send a quick “busy, talk soon.”','Wait until I can give a real answer.','Reply when my day is done.']},
  {topic:'NON-NEGOTIABLES',q:'They want something from a relationship that you don’t. What comes first?',a:['Ask why it matters to them.','Explain my own limit clearly.','Take time to decide whether we fit.']},
  {topic:'KEEPING AGREEMENTS',q:'You made plans, then something better comes up. What do you do?',a:['Keep our plans.','Ask if changing plans would be okay.','Suggest another time.']}
];
const TESTS=[['Love Language','How you show and receive affection','love-language'],['Attachment','How you respond to closeness and distance','attachment'],['Communication Style','How you start and repair conversations','communication-style'],['Emotional Expression','How you share feelings','emotional-expression'],['Personality','Patterns that shape how you relate','personality']];
const KEY='chempatibility.walkthrough.v6';
const invitationToken=new URLSearchParams(location.search).get('invite');
// A new key starts everyone with a clean walkthrough after this deployment.
try{for(const old of ['v2','v3','v4','v5'])sessionStorage.removeItem(`chempatibility.walkthrough.${old}`)}catch{}
const blank=()=>({view:'landing',joinStep:1,actor:'member',member:{name:'',contact:'',photo:'',answers:[]},prospect:{name:'',phone:'',email:'',photo:'',answers:[]},connectionId:'',liveInvite:false,liveToken:'',liveMember:false,liveId:'',inbox:[],memberQuestionsOpen:false,prospectQuestionsOpen:false,phase:'registration',index:0,pick:null,modal:'',messages:[],notice:'',testRequest:''});
let s;try{s={...blank(),...JSON.parse(sessionStorage.getItem(KEY)||'{}')}}catch{s=blank()}
if(!['landing','dashboard','profile','questions','invitee','revealPhoto','results','request','conversation','email','tests'].includes(s.view))s.view='landing';
if(s.view==='request'&&['request','declined'].includes(s.phase)&&s.actor==='prospect')s.view='profile';
if(s.view==='questions'&&s.actor==='member'){s.view='dashboard';s.memberQuestionsOpen=true}
if(s.view==='questions'&&s.actor==='prospect'&&s.phase!=='secondFive'&&s.prospect.answers.length<5){s.view='invitee';s.prospectQuestionsOpen=true}
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const first=x=>(x||'Friend').trim().split(/\s+/)[0];
const name=a=>first(a==='member'?s.member.name:s.prospect.name);
const photo=a=>a==='member'?s.member.photo:s.prospect.photo;
const face=(a,size='')=>`<span class="face ${size}">${photo(a)?`<img src="${photo(a)}" alt="${esc(name(a))}">`:esc(name(a)[0])}</span>`;
const personCard=(a,caption)=>`<div class="personCard">${face(a)}<span><small>${esc(caption)}</small><b>${esc(name(a))}</b></span></div>`;
const pairTag=()=>s.connectionId?`<span class="pairTag">Connection ${esc(s.connectionId)}</span>`:'';
function ensureConnection(){if(!s.connectionId)s.connectionId='CP-'+(globalThis.crypto?.randomUUID?.().slice(0,8)||Math.random().toString(36).slice(2,10)).toUpperCase()}
const button=(label,action,style='')=>`<button type="button" class="button ${style}" onclick="${action}">${label}</button>`;
const save=()=>{try{sessionStorage.setItem(KEY,JSON.stringify(s))}catch{ /* Camera images may exceed browser storage; this tab still works. */ }};
const mask=phone=>phone?`••• ••• ${phone.replace(/\D/g,'').slice(-4)}`:'Phone pending';
const steps=()=>`<div aria-label="Game stages"><span class="miniStep">1 · My ten</span><span class="miniStep">2 · Their first five</span><span class="miniStep">3 · Reveal &amp; request</span><span class="miniStep">4 · Chat &amp; next five</span></div>`;
function render(){save();let actor=s.actor; $('navUser').innerHTML=s.view==='landing'?'':`<div class="user">${face(actor)}<span><b>${esc(name(actor))}</b><small>My page</small></span><button class="navHome" type="button" onclick="goHome()">MY PAGE</button></div>`;
let html='';
if(s.view==='landing')html=`<div class="hero joinHero"><div class="eyebrow">CHEMPATIBILITY</div><h1>Chem-<em>patibility</em>: IYKYK!</h1><p>Chemistry and compatibility make for the memories.</p></div><section class="box joinCard">${s.joinStep===2?`<div class="eyebrow">2 · YOUR PICTURE</div><h2>Add your picture.</h2><p>Let them see who they’re playing with.</p><div class="photoActions"><input id="memberPhoto" type="file" accept="image/*" onchange="uploadPhoto(event,'member')" hidden><input id="memberCameraInput" type="file" accept="image/*" capture="user" onchange="uploadPhoto(event,'member')" hidden><button type="button" class="button alt" onclick="$('memberPhoto').click()">CHOOSE PHOTO</button><button type="button" class="button alt" onclick="$('memberCameraInput').click()">TAKE PHOTO</button></div><p id="joinError" class="error" role="alert"></p><button type="button" class="link" onclick="backToDetails()">← Back to details</button>`:`<div class="eyebrow">1 · YOUR DETAILS</div><h2>Let’s get you in.</h2><p>Start with your name and a way to reach you.</p><input class="joinInput" id="joinName" aria-label="Your name" autocomplete="given-name" maxlength="50" placeholder="Your first name" value="${esc(s.member.name)}"><input class="joinInput" id="joinContact" aria-label="Email or cell" autocomplete="email" placeholder="Email or cell" value="${esc(s.member.contact)}"><button type="button" class="button nextButton" onclick="nextJoinStep()">NEXT STEP →</button><p id="joinError" class="error" role="alert"></p>`}</section>`
if(s.view==='dashboard'){
 const answered=s.member.answers.length,ready=answered===10,q=QUESTIONS[answered];
 html=`<div class="hero"><div class="eyebrow">MY PAGE</div><h1>Hi, ${esc(name('member'))}.</h1><p>Meet someone interesting? Give them a way to know you.</p></div>
 ${s.phase==='firstResults'?`<div class="notice"><b>Your first five just opened.</b> Someone played, and your answers are ready to compare. <button class="link" onclick="navigate('results','member')">SEE OUR ANSWERS →</button></div>`:''}
 <section class="introCard memberIntro"><div class="introPitch"><div class="eyebrow">${ready?'READY TO CONNECT':'STEP 3 · MAKE IT YOURS'}</div><h2>${ready?'Your five are ready to reveal.':'The best conversations start with your answers.'}</h2><p>${ready?'Someone catches your eye? Invite them to play. You’ll both see the answers after their five.':'Ten quick situations. Choose what you’d really do. Your first five stay hidden until the other person plays.'}</p>${!ready&&!s.memberQuestionsOpen?button(answered?'CONTINUE MY TEN →':'LET’S PLAY MY TEN →','startMemberQuestions()'):''}</div>
 <div id="memberQuestion" class="memberQuestion">${ready?`<div class="eyebrow">THE GAME IS ON</div><h3>Who caught your eye?</h3><p>Show them your invitation. Their five answers unlock yours.</p>${button('INVITE THEM →','openInvite()')}`:s.memberQuestionsOpen?`<div class="eyebrow">QUESTION ${answered+1} OF 10 · ${esc(q.topic)}</div><h3>${esc(q.q)}</h3><div class="progress">${Array.from({length:10},(_,i)=>`<span class="${i<=answered?'done':''}"></span>`).join('')}</div>${q.a.map((a,i)=>`<button type="button" class="option ${s.pick===i?'on':''}" aria-pressed="${s.pick===i}" onclick="pick(${i})">${'ABC'[i]}. ${esc(a)}</button>`).join('')}${button(answered===9?'FINISH MY TEN →':'SAVE & NEXT →','answerQuestion()')}<p id="answerError" class="error" role="alert"></p>`:`<div class="eyebrow">YOUR TEN</div><h3>One question at a time.</h3><p>Tap Let’s Play to put your first answer here.</p>`}</div></section>
 <div class="grid dashboardLower"><section class="box"><h2>My invitation</h2><p>${ready?'Show your code to someone you met. The visitor gets your photo, first name, and Five to Vibe.':'Your invitation opens when your ten answers are in.'}</p>${ready?`<div class="row">${button('OPEN INVITATION →','openInvite()','alt')}${button('SIMULATE A SCAN →','simulateScan()','light')}</div>`:''}</section><section class="box"><h2>Chempats</h2>${s.liveMember&&s.inbox.length?s.inbox.map(c=>`<button class="connection" onclick="selectLiveConnection('${c.id}')">${c.prospect_photo?`<span class="face"><img src="${c.prospect_photo}" alt=""></span>`:`<span class="face">${esc(first(c.recipient_name)[0])}</span>`}<span><b>${esc(c.prospect_name||c.recipient_name)}</b><br><small>${esc(({invited:'Invitation sent',firstResults:'First five revealed',request:'Connection request · Your move',chat:'Chat open',secondResults:'Next five revealed',email:'Email shared',declined:'Passed'})[c.status]||'Connection open')}</small></span><span>→</span></button>`).join(''):s.prospect.answers.length?`<button class="connection" onclick="showConnection()">${face('prospect')}<span><b>${esc(name('prospect'))}</b><br><small>${esc(connectionStatus())}</small></span><span>→</span></button>`:'<p>Your invitations and conversations appear here.</p>'}${s.phase==='request'&&(!s.liveMember||s.liveId)?`<div class="decisionCard">${personCard('prospect','Wants to connect with you')}<p>${esc(name('prospect'))} answered your first five and wants to talk. ${s.prospect.phone?`Cell ${esc(mask(s.prospect.phone))}.`:'Email shared privately.'}</p>${pairTag()}<div class="row">${button('ACCEPT & OPEN CHAT →','acceptRequest()')}${button('PASS','declineRequest()','light')}</div></div>`:''}${s.phase==='declined'?`<div class="decisionCard">${personCard('prospect','Connection passed')}<p>You passed on this request.</p>${pairTag()}</div>`:''}${s.phase==='chat'||s.phase==='secondFive'||s.phase==='email'||s.phase==='tests'?`<div class="row">${button('OPEN OUR SPACE →','openConversation()','alt')}</div>`:''}</section></div>
 ${ready?`<details class="box myTen thinkCard"><summary><span><span class="eyebrow">A LITTLE MORE ABOUT YOU</span><strong>Your ten, when you want them.</strong><small>Your choices are here to revisit.</small></span><b>VIEW MY ANSWERS →</b></summary><ol class="answeredList">${QUESTIONS.map((item,i)=>`<li><strong>${esc(item.q)}</strong><span>${esc(item.a[s.member.answers[i]])}</span></li>`).join('')}</ol></details>`:''}`;
}
if(s.view==='profile')html=`<div class="hero compactHero"><div class="eyebrow">MY PAGE</div><h1>Hey, ${esc(name('prospect'))}.</h1><p>${s.phase==='request'?'Your move is in. Now it’s their turn.':s.phase==='declined'?'This one didn’t open.':'The conversation is open. Say hello.'}</p></div><div class="grid profileGrid"><section class="box"><div class="eyebrow">ME</div><div class="profileIdentity">${face('prospect')}<div><h2>${esc(name('prospect'))}</h2><p>${esc(s.prospect.email||mask(s.prospect.phone))}</p></div></div><p>You played ${s.prospect.answers.length} quick situations. Your answers are part of this connection.</p></section><section class="box"><div class="eyebrow">CHEMPATS</div><div class="profileConnection"><div class="peopleBar">${face('prospect')}<span>+</span>${face('member')}</div><b>${esc(name('member'))}</b><p>${s.phase==='request'?'Request sent · waiting for their answer':s.phase==='declined'?'They passed on this request.':'Chat open · your next five are waiting'}</p>${['chat','secondResults','email','tests'].includes(s.phase)?button('OPEN OUR CHAT →','openConversation()'):''}</div></section></div>`;
if(s.view==='questions'){let member=s.actor==='member',offset=member?0:(s.phase==='secondFive'?5:0),count=member?10:5,answers=member?s.member.answers:s.prospect.answers,index=answers.length-offset,q=QUESTIONS[offset+index];if(index>=count){s.view=member?'dashboard':'results';return render()}html=`<div class="hero"><div class="eyebrow">${member?'MAKE YOUR PAGE':'FIVE TO VIBE'} · ${index+1} OF ${count}</div><h1>${member?'Your answers make the introduction.':'Pick what you’d actually do.'}</h1><p>${member?'The first five are revealed only after someone plays.':'Your answers and theirs will reveal together.'}</p></div><div class="progress">${Array.from({length:count},(_,i)=>`<span class="${i<=index?'done':''}"></span>`).join('')}</div><div class="grid"><section class="question"><div class="eyebrow">${esc(q.topic)}</div><h2>${esc(q.q)}</h2>${q.a.map((a,i)=>`<button type="button" class="option ${s.pick===i?'on':''}" aria-pressed="${s.pick===i}" onclick="pick(${i})">${'ABC'[i]}. ${esc(a)}</button>`).join('')}<div class="row">${button(index===count-1?(member?'FINISH MY TEN →':offset?'REVEAL OUR NEXT FIVE →':'REVEAL OUR FIRST FIVE →'):'NEXT →','answerQuestion()')}</div><p id="answerError" class="error" role="alert"></p></section><aside class="box"><h3>${member?'The game begins with you.':`${esc(name('member'))} answered already.`}</h3><p>${member?'Answer all ten, then show your invitation. You can see your choices again on your page.':'Pick your own answer. Both sets reveal when you finish these five.'}</p></aside></div>`}
if(s.view==='invitee'){
 const answered=s.prospect.answers.length,q=QUESTIONS[answered]||QUESTIONS[0];
 html=`<div class="inviteeHero"><div class="hero compactHero"><div class="eyebrow">AN INVITATION FOR YOU</div><h1>Five to Vibe.</h1><p>Answer five quick situations. Then you both see how you answered.</p></div><div class="inviterIdentity">${face('member')}<span><small>Invited you to play</small><b>${esc(name('member'))}</b></span></div></div>
 <section class="introCard memberIntro"><div class="introPitch"><div class="eyebrow">${answered?'FIVE TO VIBE · IN PROGRESS':'FIVE TO VIBE'}</div><h2>“I like your vibe. Tell me more!”</h2><p>Pick your answers to five quick situations. Then you’ll see how you both answered.</p>${!s.prospectQuestionsOpen?button(answered?'CONTINUE MY FIVE →':'I’LL PLAY — GO →','startProspect()'):''}</div>
 <div id="prospectQuestion" class="memberQuestion">${s.prospectQuestionsOpen?`<div class="eyebrow">QUESTION ${answered+1} OF 5 · ${esc(q.topic)}</div><h3>${esc(q.q)}</h3><div class="progress">${Array.from({length:5},(_,i)=>`<span class="${i<=answered?'done':''}"></span>`).join('')}</div>${q.a.map((a,i)=>`<button type="button" class="option ${s.pick===i?'on':''}" aria-pressed="${s.pick===i}" onclick="pick(${i})">${'ABC'[i]}. ${esc(a)}</button>`).join('')}${button(answered===4?'REVEAL OUR FIRST FIVE →':'SAVE & NEXT →','answerQuestion()')}<p id="answerError" class="error" role="alert"></p>`:`<div class="eyebrow">YOUR FIVE</div><h3>One question at a time.</h3><p>Tap Play My Five to put your first answer here.</p>`}</div></section>`;
}
if(s.view==='revealPhoto')html=`<section class="box revealPhotoStep"><div class="eyebrow">YOUR FIVE ARE IN</div><h2>Put a face to your answers.</h2><p>Add your picture, then see how you both answered.</p><div class="photoActions"><input id="revealPhotoInput" type="file" accept="image/*" onchange="uploadPhoto(event,'prospect')" hidden><input id="revealCameraInput" type="file" accept="image/*" capture="user" onchange="uploadPhoto(event,'prospect')" hidden><button type="button" class="button alt" onclick="$('revealPhotoInput').click()">CHOOSE PHOTO</button><button type="button" class="button light" onclick="$('revealCameraInput').click()">TAKE PHOTO</button></div><p id="revealPhotoError" class="error" role="alert"></p></section>`;
if(s.view==='results'){let offset=s.phase==='secondResults'||s.phase==='email'||s.phase==='tests'?5:0;html=`<div class="revealIntro"><div class="eyebrow">${offset?'NEXT FIVE':'FIRST FIVE'} · BOTH SIDES</div><h2>How you answered.</h2></div><section class="box revealBoard"><div class="revealPeople"><div aria-label="${esc(name('member'))}'s answers">${face('member')}</div><div aria-label="${esc(name('prospect'))}'s answers">${face('prospect')}</div></div>${QUESTIONS.slice(offset,offset+5).map((q,i)=>{const left=q.a[s.member.answers[offset+i]]||'Waiting',right=q.a[s.prospect.answers[offset+i]]||'Waiting',match=s.member.answers[offset+i]!==undefined&&s.member.answers[offset+i]===s.prospect.answers[offset+i];return `<div class="revealItem"><div class="revealQuestion"><span>${i+1} · ${esc(q.topic)}</span><strong>${esc(q.q)}</strong></div><div class="revealChoices"><button type="button" class="revealChoice ${match?'match matchLight':'different'}" title="${esc(left)}" aria-label="${esc(name('member'))}: ${esc(left)}" onclick="this.classList.toggle('expanded')">${esc(left)}</button><button type="button" class="revealChoice ${match?'match matchDark':'different'}" title="${esc(right)}" aria-label="${esc(name('prospect'))}: ${esc(right)}" onclick="this.classList.toggle('expanded')">${esc(right)}</button></div></div>`}).join('')}<div class="row revealNext">${offset?button('CONTINUE →','continueAfterSecond()'):s.actor==='prospect'?button('I’D LIKE TO CONNECT →','showRequest()'):button('MY PAGE →','goHome()','alt')}</div></section>`}
if(s.view==='request')html=`<div class="hero compactHero"><div class="eyebrow">KEEP THE VIBE GOING</div><h1>Want to talk with ${esc(name('member'))}?</h1><p>Let them know it’s you. If they’re in, your chat opens here.</p></div><div class="box requestCard">${personCard('member','Your invitation from')}${pairTag()}<div class="requestForm"><input class="joinInput" id="prospectName" aria-label="First name" autocomplete="given-name" maxlength="50" value="${esc(s.prospect.name)}" placeholder="First name"><div class="requestPhoto"><div class="requestPhotoLead">${face('prospect')}<span><b>Your picture</b><small>${s.prospect.photo?'This is the picture they’ll see.':'Give them a face to meet.'}</small></span></div><div class="photoActions"><input id="requestPhotoInput" type="file" accept="image/*" onchange="uploadPhoto(event,'prospect')" hidden><input id="requestCameraInput" type="file" accept="image/*" capture="user" onchange="uploadPhoto(event,'prospect')" hidden><button type="button" class="button alt" onclick="$('requestPhotoInput').click()">${s.prospect.photo?'CHANGE PHOTO':'CHOOSE PHOTO'}</button><button type="button" class="button light" onclick="$('requestCameraInput').click()">TAKE PHOTO</button></div></div><input class="joinInput" id="prospectContact" aria-label="Email or cell" autocomplete="email" value="${esc(s.prospect.email||s.prospect.phone)}" placeholder="Email or cell"><p class="small">Your contact stays private while they decide.</p><div class="row">${button('ASK TO CONNECT →','sendRequest()')}</div><p class="error" id="requestError" role="alert"></p></div></div>`;
if(s.view==='conversation'){let nextReady=s.prospect.answers.length===10;html=`<div class="hero chatHeader"><div class="eyebrow">OUR SPACE · ${esc(name('member'))} + ${esc(name('prospect'))}</div><h1>Private Chat</h1><div class="chatPair"><div class="chatPerson">${face('member')}<b>${esc(name('member'))}</b></div><div class="chatPerson">${face('prospect')}<b>${esc(name('prospect'))}</b></div></div><p>You both saw the first five. Say what’s on your mind.</p><button type="button" class="link" onclick="goHome()">← MY PAGE</button></div><div class="grid"><section class="box"><h2>Private Chat</h2><div class="chat">${s.messages.length?s.messages.map(m=>`<div class="chatLine ${m.by===s.actor?'mine':''}">${face(m.by)}<p><b>${esc(name(m.by))}</b><br>${esc(m.text)}</p></div>`).join(''):'<p>Say hello. The first five gave you something to start with.</p>'}</div><label class="field">Message as ${esc(name(s.actor))}<input id="message" maxlength="500" placeholder="Say something…" onkeydown="if(event.key==='Enter')sendMessage()"></label><div class="row">${button('SEND →','sendMessage()','alt')}</div></section><aside class="stack"><div class="box"><h3>Five more to unlock email and more.</h3><p>${nextReady?'Both sets of answers are ready to see.':s.actor==='prospect'?'Keep playing to reveal more.':'The next five are ready for them when they come back.'}</p><div class="row">${nextReady?button('SEE OUR NEXT FIVE →','showSecondResults()'):s.actor==='prospect'?button('PLAY THE NEXT FIVE →','startSecondFive()'):''}</div></div><div class="box"><h3>Connection</h3><p>${esc(name('prospect'))} · ${esc(mask(s.prospect.phone))}</p><p class="small">Email comes after the next five.</p></div></aside></div>`}
if(s.view==='email')html=`<div class="hero"><div class="eyebrow">TEN ANSWERS IN</div><h1>Keep this connection close.</h1><p>Five to Vibe gave you a start. There’s more to discover together.</p></div><section class="box" style="max-width:530px"><h2>Your email and more.</h2><p>Save an email for the next chapter of your conversation.</p>${s.actor==='prospect'?`<label class="field">Your email<input id="prospectEmail" type="email" autocomplete="email" value="${esc(s.prospect.email)}" placeholder="you@example.com"></label><div class="row">${button('SAVE & SEE WHAT’S NEXT →','saveEmail()')}</div><p id="emailError" class="error" role="alert"></p>`:`<p>${s.prospect.email?'Email provided for this preview.':'Waiting for their email.'}</p>${button('SEE WHAT’S NEXT →','showTests()')}`}</section>`;
if(s.view==='tests')html=`<div class="hero"><div class="eyebrow">GO DEEPER TOGETHER</div><h1>Choose what to explore next.</h1><p>Either person can take a test, then invite the other to take that same test. Results will reveal after both finish.</p></div><div class="grid"><section class="box"><h2>Shared tests</h2>${TESTS.map(t=>`<div class="testCard"><b>${esc(t[0])}</b><p>${esc(t[1])}</p><a href="/admin#questions/test-${t[2]}" target="_blank" rel="noopener">Read the test brief →</a></div>`).join('')}</section><aside class="box"><h3>Coming into the game</h3><p>These links open test briefs. The assessments, invitations, and mutual results screens have not been built yet.</p><div class="row">${button('BACK TO OUR CHAT →','openConversation()','alt')}</div></aside></div>`;
if(s.notice)html=`<div class="notice" role="status">${esc(s.notice)}</div>`+html;
$('root').innerHTML=html;renderModal();}
function navigate(view,actor){s.view=view;if(actor)s.actor=actor;s.pick=null;s.notice='';render();window.scrollTo(0,0)}
function goHome(){if(s.actor==='prospect'&&!s.liveInvite){navigate('profile','prospect');return}if(s.liveInvite){navigate(['request','chat','secondResults','email','tests','declined'].includes(s.phase)?'profile':s.prospect.answers.length>=5?'results':'invitee','prospect');return}navigate(s.member.answers.length?'dashboard':'landing','member')}
function nextJoinStep(){const n=$('joinName').value.trim(),c=$('joinContact').value.trim();if(!n||!c){$('joinError').textContent='Enter your name and email or cell.';return}s.member.name=n;s.member.contact=c;s.joinStep=2;render()}
function backToDetails(){cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;s.joinStep=1;render()}
let cameraStream=null;
async function openCamera(){
 const error=$(s.view==='request'?'requestError':s.view==='revealPhoto'?'revealPhotoError':'joinError');error.textContent='';
 if(!navigator.mediaDevices?.getUserMedia){error.textContent='Camera unavailable. Tap CHOOSE PHOTO instead.';return}
 try{
  cameraStream?.getTracks().forEach(t=>t.stop());
  cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});
  const video=$('cameraPreview');video.srcObject=cameraStream;video.hidden=false;$('captureBtn').hidden=false;
  await video.play();
 }catch(e){cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;error.textContent='Camera unavailable. Tap CHOOSE PHOTO instead.'}
}
async function captureCamera(){
 const video=$('cameraPreview');if(!video?.videoWidth){$(s.view==='request'?'requestError':s.view==='revealPhoto'?'revealPhotoError':'joinError').textContent='Wait for the camera, then capture your picture.';return}
 const canvas=$('cameraCanvas'),side=Math.min(video.videoWidth,video.videoHeight);canvas.width=canvas.height=320;
 canvas.getContext('2d').drawImage(video,(video.videoWidth-side)/2,(video.videoHeight-side)/2,side,side,0,0,320,320);
 const picture=canvas.toDataURL('image/jpeg',.78);if(s.view==='landing')s.member.photo=picture;else s.prospect.photo=picture;
 cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;
 video.srcObject=null;video.hidden=true;$('captureBtn').hidden=true;
 if(s.view==='landing')finishRegistration();
 else if(s.view==='revealPhoto'){try{await recordFirstFive();s.phase='firstResults';navigate('results','prospect')}catch(e){$('revealPhotoError').textContent=e.message||'Could not save your answers. Try again.'}}
 else{const n=$('prospectName').value,c=$('prospectContact').value;render();$('prospectName').value=n;$('prospectContact').value=c}
 save();
}
async function uploadPhoto(event,actor){
 const file=event.target.files?.[0];if(!file)return;
 const target=actor==='member'?'joinError':s.view==='revealPhoto'?'revealPhotoError':'requestError';
 if(!file.type.startsWith('image/')){$(target).textContent='Choose an image file.';return}
 try{
  const data=await new Promise((resolve,reject)=>{
   const img=new Image(),url=URL.createObjectURL(file);
   img.onload=()=>{try{const canvas=document.createElement('canvas');canvas.width=canvas.height=320;const side=Math.min(img.width,img.height);canvas.getContext('2d').drawImage(img,(img.width-side)/2,(img.height-side)/2,side,side,0,0,320,320);resolve(canvas.toDataURL('image/jpeg',.78))}catch(e){reject(e)}finally{URL.revokeObjectURL(url)}};
   img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Could not open this picture.'))};img.src=url;
  });
  if(actor==='member')s.member.photo=data;else s.prospect.photo=data;
  if(actor==='member'){cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;const v=$('cameraPreview');if(v){v.srcObject=null;v.hidden=true}$(target).textContent='';finishRegistration()}
  else if(s.view==='revealPhoto'){await recordFirstFive();s.phase='firstResults';navigate('results','prospect')}else{cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;const n=$('prospectName').value,c=$('prospectContact').value;render();$('prospectName').value=n;$('prospectContact').value=c}
  save();
 }catch(e){$(target).textContent=e.message||'Could not open this picture.'}
}
function resetWalkthrough(){
 if(!confirm('Clear this page in this browser tab? This does not clear sent invitations or the database.'))return;
 cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;
 try{for(const version of ['v2','v3','v4','v5','v6'])sessionStorage.removeItem(`chempatibility.walkthrough.${version}`)}catch{}
 s=blank();render();window.scrollTo(0,0);
}
function finishRegistration(){if(!s.member.name||!s.member.contact||!s.member.photo){$('joinError').textContent='Complete your details and picture to continue.';return}s.modal='welcome';renderModal();save()}
function enterGame(){s.modal='';navigate('dashboard','member')}
function startMemberQuestions(){s.actor='member';s.view='dashboard';s.memberQuestionsOpen=true;s.pick=null;render();$('memberQuestion')?.scrollIntoView({behavior:'smooth',block:'nearest'})}
function pick(i){s.pick=i;document.querySelectorAll('.option').forEach((el,j)=>{el.classList.toggle('on',j===i);el.setAttribute('aria-pressed',j===i)})}
async function answerQuestion(){if(s.pick===null){$('answerError').textContent='Pick one answer to continue.';return}let member=s.actor==='member',arr=member?s.member.answers:s.prospect.answers;arr.push(s.pick);s.pick=null;if(member&&arr.length===10){s.memberQuestionsOpen=false;s.phase='ready';navigate('dashboard','member')}else if(!member&&arr.length===5){s.phase=s.prospect.photo?'firstResults':'awaitingPhoto';navigate(s.prospect.photo?'results':'revealPhoto','prospect')}else if(!member&&arr.length===10){try{if(s.liveInvite){await connectionApi({action:'second',token:s.liveToken,answers:arr});await refreshLive()}s.phase='secondResults';navigate('results','prospect')}catch(e){arr.pop();$('answerError').textContent=e.message}}else render()}
function openInvite(){if(s.member.answers.length!==10)return;ensureConnection();s.modal='qr';renderModal();save()}
function closeInvite(e){if(e&&e.target!==e.currentTarget)return;s.modal='';renderModal()}
function inviteMode(m){s.modal=m;renderModal()}
function renderModal(){let host=$('modalHost');if(!s.modal){host.innerHTML='';return}if(s.modal==='welcome'){host.innerHTML=`<div class="modalBackdrop" onclick="closeInvite(event)"><section class="modal welcomeModal" role="dialog" aria-modal="true" aria-labelledby="welcomeTitle"><button class="close" type="button" aria-label="Close" onclick="closeInvite()">×</button><div class="eyebrow">3 · YOUR PAGE</div><div class="welcomeFace">${face('member')}</div><h2 id="welcomeTitle">Ready to play, ${esc(name('member'))}?</h2><p>Your page is next. Answer ten quick situations to make it yours, then invite someone into your first five.</p>${button('STEP 3 — OPEN MY PAGE →','enterGame()')}<p class="small">Your page is ready for you.</p></section></div>`;return}host.innerHTML=`<div class="modalBackdrop" onclick="closeInvite(event)"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="inviteTitle"><button class="close" type="button" aria-label="Close invitation" onclick="closeInvite()">×</button><div class="eyebrow">YOUR INVITATION</div><h2 id="inviteTitle">${s.modal==='qr'?`I like your vibe. Tell me more!`:'I caught your vibe. Let’s talk.'}</h2>${s.modal==='qr'?`<div class="invitePair"><div>${s.member.photo?`<img class="portrait" src="${s.member.photo}" alt="${esc(name('member'))}">`:face('member')}<b style="display:block;margin-top:8px">${esc(name('member'))}</b></div><div><div class="placeholderQr" aria-label="QR preview; use simulate scan to try this walkthrough"><span>SCAN ME</span></div></div></div><p class="small">Scan preview · email invitations are available below.</p><button class="link" type="button" onclick="inviteMode('send')">Can’t scan? Send it instead →</button><div class="demo"><button class="link" type="button" onclick="simulateScan()">Simulate a scan on this device →</button></div>`:`<div class="modalForm"><p class="small">Send your picture, name, and “Let’s talk!” to their email. We’ll verify your email first.</p><label class="field">Their name<input id="inviteName" autocomplete="given-name" maxlength="50" placeholder="First name"></label><label class="field">Their email<input id="inviteContact" type="email" autocomplete="email" placeholder="them@example.com"></label><div class="row">${button('SEND INVITATION →','prepareInvite()')}</div><p id="inviteError" class="error" role="alert"></p><button class="link" type="button" onclick="inviteMode('qr')">← Show code instead</button></div>`}</section></div>`}
async function connectionApi(data){const response=await fetch('/api/connection',{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify(data)});let body;try{body=await response.json()}catch{throw Error('Connection service did not respond.')}if(!response.ok)throw Error(body.error||'Could not update the connection.');return body}
async function emailApi(data){const response=await fetch('/api/email',{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify(data)});let body;try{body=await response.json()}catch{throw Error('The email service did not respond.')}if(!response.ok)throw Error(body.error||'Could not send the email.');return body}
let pendingInvite=null;
async function prepareInvite(){let n=$('inviteName').value.trim(),c=$('inviteContact').value.trim().toLowerCase(),error=$('inviteError');if(!n||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c)){error.textContent='Enter their name and email.';return}pendingInvite={name:n,email:c};error.textContent='Checking your email…';try{const status=await fetch('/api/email',{credentials:'same-origin'}).then(r=>r.json());if(status.email&&status.email===s.member.contact.trim().toLowerCase())return await sendInvitation();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s.member.contact)){error.textContent='Your own contact needs to be an email address to send invitations. Update it in your details.';return}await emailApi({action:'start',email:s.member.contact});renderVerify()}catch(e){error.textContent=e.message}}
function renderVerify(){s.modal='verify';$('modalHost').innerHTML=`<div class="modalBackdrop" onclick="closeInvite(event)"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="verifyTitle"><button class="close" type="button" aria-label="Close" onclick="closeInvite()">×</button><div class="eyebrow">ONE QUICK CHECK</div><h2 id="verifyTitle">Check your email.</h2><p>Enter the six digit code sent to ${esc(s.member.contact)}. Then we’ll send your invitation to ${esc(pendingInvite.name)}.</p><div class="modalForm"><label class="field">Your code<input id="emailCode" inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="000000"></label>${button('VERIFY & SEND →','verifyAndSend()')}<p id="verifyError" class="error" role="alert"></p></div></section></div>`}
async function verifyAndSend(){const error=$('verifyError');error.textContent='Verifying…';try{await emailApi({action:'verify',email:s.member.contact,code:$('emailCode').value.trim()});const button=error.closest('.modalForm').querySelector('button');button.textContent='RETRY SEND →';button.setAttribute('onclick','sendInvitation()');$('emailCode').disabled=true;await sendInvitation()}catch(e){error.textContent=e.message}}
async function sendInvitation(){const error=$('verifyError')||$('inviteError');error.textContent='Sending…';try{const sent=await emailApi({action:'send',member:s.member,recipient:pendingInvite});s.liveMember=true;s.liveId=sent.id;s.prospect.name=pendingInvite.name;ensureConnection();s.modal='';navigate('dashboard','member');s.notice=`Invitation sent to ${first(pendingInvite.name)}. You’ll see them in Chempats.`;render();refreshLive()}catch(e){error.textContent=e.message}}
async function openEmailInvitation(){if(!invitationToken)return;try{const response=await fetch(`/api/connection?invite=${encodeURIComponent(invitationToken)}`,{cache:'no-store'}),data=await response.json();if(!response.ok)throw Error(data.error||'Invitation unavailable.');s=blank();s.member.name=data.name;s.member.photo=data.photo;s.member.answers=data.answers;s.liveInvite=true;s.liveToken=invitationToken;s.prospect.name=data.prospectName||data.recipientName;s.prospect.photo=data.prospectPhoto||'';s.prospect.answers=data.prospectAnswers||[];s.prospect.phone=data.prospectPhone||'';s.prospect.email=data.prospectEmail||'';s.messages=data.messages||[];s.actor='prospect';s.phase=data.status;s.view=['request','declined'].includes(data.status)?'profile':data.status==='chat'?'conversation':data.status==='secondResults'?'results':data.status==='email'?'tests':data.status==='firstResults'?'results':'invitee';history.replaceState(null,'',location.pathname);render()}catch(e){s=blank();s.notice=e.message;render()}}
async function recordFirstFive(){if(s.liveInvite){const data=await connectionApi({action:'first',token:s.liveToken,answers:s.prospect.answers.slice(0,5),photo:s.prospect.photo});s.member.answers=data.answers}}
function applyConnection(c){s.prospect.name=c.prospect_name||c.recipient_name||s.prospect.name;s.prospect.photo=c.prospect_photo||s.prospect.photo;s.prospect.answers=c.prospect_answers||s.prospect.answers;s.prospect.phone=c.prospect_phone||s.prospect.phone;s.prospect.email=c.prospect_email||s.prospect.email;s.messages=c.messages||s.messages;s.phase=c.status}
function selectLiveConnection(id){const c=s.inbox.find(item=>item.id===id);if(!c)return;s.liveId=id;applyConnection(c);if(c.status==='firstResults')navigate('results','member');else if(['chat','secondResults','email','tests'].includes(c.status))navigate('conversation','member');else navigate('dashboard','member')}
let refreshing=false;
async function refreshLive(){if(refreshing||document.hidden||(!s.liveMember&&!s.liveInvite))return;refreshing=true;try{
 if(s.liveMember){const response=await fetch('/api/connection?inbox=1',{credentials:'same-origin',cache:'no-store'}),data=await response.json();if(!response.ok)throw Error(data.error);const before=JSON.stringify(s.inbox),previous=s.phase;s.inbox=data.connections||[];if(!s.liveId&&s.inbox.length)s.liveId=s.inbox[0].id;const selected=s.inbox.find(c=>c.id===s.liveId);if(selected)applyConnection(selected);if(before!==JSON.stringify(s.inbox)&&['dashboard','conversation','request','results'].includes(s.view)&&document.activeElement?.id!=='message')render();if(previous!=='request'&&s.phase==='request'&&s.view==='dashboard')render()}
 else{const response=await fetch(`/api/connection?invite=${encodeURIComponent(s.liveToken)}`,{cache:'no-store'}),data=await response.json();if(!response.ok)throw Error(data.error);const previous=s.phase,oldMessages=JSON.stringify(s.messages);s.member.answers=data.answers;s.messages=data.messages||[];if(data.prospectAnswers?.length>s.prospect.answers.length)s.prospect.answers=data.prospectAnswers;if(!(s.view==='questions'&&s.prospect.answers.length>=5))s.phase=data.status;if(previous!==s.phase&&s.view==='profile')render();else if(s.view==='conversation'&&oldMessages!==JSON.stringify(s.messages))render()}
 save()
 }catch(e){if(['Invitation not found.','Verify your email to see connections.'].includes(e.message)){s=blank();render()}else{s.notice=e.message;render()}}finally{refreshing=false}}
function simulateScan(){if(s.member.answers.length!==10)return;ensureConnection();s.modal='';s.phase='invited';navigate('invitee','prospect')}
function startProspect(){if(s.prospect.answers.length>=5){navigate(s.prospect.photo?'results':'revealPhoto','prospect');return}s.actor='prospect';s.view='invitee';s.prospectQuestionsOpen=true;s.pick=null;render();$('prospectQuestion')?.scrollIntoView({behavior:'smooth',block:'nearest'})}
function showRequest(){ensureConnection();navigate('request','prospect')}
async function sendRequest(){let n=$('prospectName').value.trim(),c=$('prospectContact').value.trim().toLowerCase(),isEmail=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c),isCell=!isEmail&&c.length<=30&&c.replace(/\D/g,'').length>=10;if(!n||(!isEmail&&!isCell)||!s.prospect.photo){$('requestError').textContent='Add your picture, first name, and an email or ten-digit cell number.';return}try{if(s.liveInvite)await connectionApi({action:'request',token:s.liveToken,name:n,contact:c,photo:s.prospect.photo});s.prospect.name=n;s.prospect.phone=isCell?c:'';s.prospect.email=isEmail?c:'';ensureConnection();s.phase='request';navigate('profile','prospect')}catch(e){$('requestError').textContent=e.message}}
async function acceptRequest(){if(s.phase!=='request')return;try{if(s.liveMember)await connectionApi({action:'decision',id:s.liveId,decision:'accept'});s.phase='chat';navigate('dashboard','member')}catch(e){s.notice=e.message;render()}}
async function declineRequest(){try{if(s.liveMember)await connectionApi({action:'decision',id:s.liveId,decision:'decline'});s.phase='declined';render()}catch(e){s.notice=e.message;render()}}
function openConversation(){navigate('conversation',s.actor)}
function showConnection(){if(s.phase==='request'||s.phase==='awaitingPhoto')navigate('dashboard','member');else if(s.phase==='firstResults')navigate('results','member');else if(s.phase==='declined')navigate('dashboard','member');else navigate('conversation','member')}
function connectionStatus(){return ({awaitingPhoto:'Five answered · photo pending',firstResults:'First five revealed',request:'Connection request · Your move',chat:'Chat open · Next five ready',secondFive:'Next five in progress',secondResults:'Next five revealed',email:'Email stage',tests:'Tests next',declined:'Request passed'})[s.phase]||'Invitation open'}
async function sendMessage(){let field=$('message'),v=field?.value.trim();if(!v)return;try{if(s.liveInvite||s.liveMember){const data=await connectionApi({action:'message',text:v,...(s.liveInvite?{token:s.liveToken}:{id:s.liveId})});s.messages=data.messages}else s.messages.push({by:s.actor,text:v});render()}catch(e){s.notice=e.message;render()}}
function startSecondFive(){if(s.phase==='declined')return;s.phase='secondFive';navigate('questions','prospect')}
function showSecondResults(){s.phase='secondResults';navigate('results',s.actor)}
function continueAfterSecond(){s.phase='email';navigate('email',s.actor)}
async function saveEmail(){let v=$('prospectEmail').value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)){$('emailError').textContent='Enter a valid email address.';return}try{if(s.liveInvite)await connectionApi({action:'email',token:s.liveToken,email:v});s.prospect.email=v;showTests()}catch(e){$('emailError').textContent=e.message}}
function showTests(){s.phase='tests';navigate('tests',s.actor)}
function switchView(){if(s.actor==='member'){if(s.phase==='ready'||s.phase==='invited')simulateScan();else if(s.phase==='awaitingPhoto')navigate('revealPhoto','prospect');else if(s.phase==='request'||s.phase==='declined')navigate('request','prospect');else if(s.phase==='firstResults')navigate(s.prospect.photo?'results':'revealPhoto','prospect');else if(s.phase==='secondFive')navigate('questions','prospect');else if(s.phase==='secondResults')navigate('results','prospect');else if(s.phase==='email')navigate('email','prospect');else navigate('conversation','prospect')}else{if(s.phase==='request'||s.phase==='awaitingPhoto')navigate('dashboard','member');else if(s.phase==='firstResults')navigate('results','member');else if(s.phase==='secondResults')navigate('results','member');else if(s.phase==='ready')navigate('dashboard','member');else navigate('conversation','member')}}
function demoNav(){let current=$('navUser');if(!s.liveInvite&&!s.liveMember&&s.view!=='landing'&&s.member.answers.length===10)current.insertAdjacentHTML('beforeend',`<button class="link" type="button" onclick="switchView()">View as ${s.actor==='member'?esc(name('prospect')):esc(name('member'))}</button>`);current.insertAdjacentHTML('beforeend','<button class="link resetLink" type="button" onclick="resetWalkthrough()">RESET THIS TAB</button>')}
const originalRender=render;render=function(){originalRender();demoNav()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&s.modal)closeInvite()});
if(invitationToken)openEmailInvitation();else{render();if(s.liveMember||s.liveInvite)refreshLive()}
setInterval(refreshLive,5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshLive()});
