import {JSDOM} from 'jsdom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8').replace('<script src="game.js"></script>','');
const source=fs.readFileSync(new URL('../game.js',import.meta.url),'utf8');
const qrRenderer=fs.readFileSync(new URL('../qr-client.js',import.meta.url),'utf8');
const photo='data:image/jpeg;base64,AA==',token='a'.repeat(64),id='b'.repeat(64);
const sender={id:'sender',name:'Cindy',contact:'cindy@example.com',photo,answers:[0,1,2,0,1,2,0,1,2,0],verified:true};
let receiver=null,qrCreates=0,lastAction=null;
const outgoingId='e'.repeat(64),outgoing={status:'invited',prospect_name:'Sam',prospect_photo:photo,prospect_answers:[],messages:[]};let outgoingCreated=false;
const calls=[],state={status:'invited',prospect_answers:[],messages:[],prospect_name:'Mike',prospect_photo:photo};
const tick=()=>new Promise(r=>setTimeout(r,15));
function page(role=null,url='https://chempatible.com/'){
 const d=new JSDOM(html,{url,runScripts:'dangerously',pretendToBeVisual:true}),w=d.window;
 let session=role;
 w.fetch=async(url,opt={})=>{
  const u=new URL(url,w.location.href),b=opt.body?JSON.parse(opt.body):{};calls.push({role:session,path:u.pathname,...b});lastAction=b;
  const connection=b.id===outgoingId?outgoing:state;
  let data={},status=200,own=session==='sender'?sender:session==='receiver'?receiver:null;
  if(u.pathname==='/api/member'){
   if(!opt.method){if(own)data={member:own};else status=401;}
   else if(b.action==='code_start')data={ok:true};
   else if(b.action==='code_verify'){if(b.code!=='123456'){status=400;data={error:'Code expired or incorrect.'}}else{const m=b.email===sender.contact?sender:receiver?.contact===b.email?receiver:null;if(m){m.verified=true;session=m===sender?'sender':'receiver'}data={existing:!!m,member:m}}}
   else if(b.action==='register'){assert.equal(b.agreed,true);receiver={id:'receiver',name:b.name,contact:b.contact,photo:b.photo,answers:b.answers||[],verified:false};session='receiver';data={member:receiver};}
   else if(b.action==='answers'){own.answers=[...b.answers];data={member:own}}
   else if(b.action==='logout'){session=null;data={ok:true}}
  }else if(u.pathname==='/api/qr'){qrCreates++;data={id:'c'.repeat(64),url:'https://chempatible.com/?invite='+'d'.repeat(64),expiresAt:new Date(Date.now()+900000).toISOString()}}
  else if(u.pathname==='/api/email'){if(b.action==='send')outgoingCreated=true;data=b.action==='send'?{id:outgoingId,ok:true}:{email:own?.contact}}
  else if(u.searchParams.has('inbox')){
   data={connections:state.status==='invited'?[]:[{id,side:session==='receiver'?'prospect':'member',...state,sender_name:sender.name,sender_photo:photo,sender_answers:['secondResults','chatRequested','chat','email','tests'].includes(state.status)?sender.answers:sender.answers.slice(0,5)},...(session==='receiver'&&outgoingCreated?[{id:outgoingId,side:'member',...outgoing}]:[])]};
  }else if(u.searchParams.has('invite'))data={name:sender.name,photo,answers:state.status==='invited'?[]:['secondResults','chatRequested','chat','email','tests'].includes(state.status)?sender.answers:sender.answers.slice(0,5),prospectName:state.prospect_name,prospectPhoto:state.status==='invited'?'':photo,prospectAnswers:state.prospect_answers,status:state.status,messages:state.messages};
  else if(b.action==='first'){assert.ok(own,'first needs account');Object.assign(state,{status:'firstResults',prospect_answers:b.answers,prospect_photo:b.photo});data={answers:sender.answers.slice(0,5)}}
  else if(b.action==='request'){if(!own?.verified){status=403;data={needsVerify:true,error:'Confirm your email.'}}else{assert.equal(b.name,receiver.name);assert.equal(b.contact,receiver.contact);state.status='request'}}
  else if(b.action==='decision'){connection.status=b.decision==='decline'?'declined':connection.status==='request'?'secondFive':'chat'}
  else if(b.action==='second'){assert.equal(connection.status,'secondFive');connection.status='secondResults';connection.prospect_answers=b.answers;data={answers:sender.answers}}
  else if(b.action==='chat'){assert.equal(connection.status,'secondResults');connection.status='chatRequested'}
  else if(b.action==='message'){assert.equal(connection.status,'chat');connection.messages.push({by:session==='sender'||b.id===outgoingId?'member':'prospect',text:b.text,photo:b.photo});data={messages:connection.messages}}
  else if(b.action==='react'){connection.messages[b.index].reactions={[b.id===outgoingId?'member':'prospect']:b.reaction};data={messages:connection.messages}}
  else if(b.action==='report'||b.action==='unmatch'){connection.status='ended';connection.messages=[];data={ok:true}}
  else if(b.action==='email'){assert.equal(connection.status,'chat');connection.status='email';data={ok:true}}
  return {ok:status===200,status,json:async()=>JSON.parse(JSON.stringify(data))};
 };
 w.eval(qrRenderer);w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
 const script=w.document.createElement('script');script.textContent=source;w.document.body.append(script);return d;
}
const pages=[];const make=(...args)=>{const p=page(...args);pages.push(p);return p};
try{
 const publicPage=make(),p=publicPage.window,doc=p.document;await tick();
 assert.match(doc.querySelector('.publicHero').textContent,/Caught a vibe/);assert.equal(doc.querySelectorAll('.examplePortrait svg').length,2);assert.equal(doc.querySelectorAll('.lockedSecrets>span').length,5);assert.match(doc.body.textContent,/Illustrative placeholder portraits.*not real members/);assert.match(doc.body.textContent,/not scannable/);assert.equal(doc.querySelectorAll('.finder').length,3);
 for(const q of p.eval('QUESTIONS')){assert.ok(!doc.querySelector('#root').textContent.includes(q.q));for(const a of q.a)assert.ok(!doc.querySelector('#root').textContent.includes(a))}
 assert.match(doc.body.textContent,/CREATE MY INSTANT VIBE/);assert.match(doc.body.textContent,/Sign up to save and return/);assert.match(doc.body.textContent,/Verify email before connecting/);
 p.eval('startFresh()');p.eval('goHome()');assert.ok(doc.querySelector('.publicHero'),'logo returns from signup to the mystery opening');p.eval('startFresh()');doc.getElementById('joinName').value='New';doc.getElementById('joinContact').value='bad';p.eval('nextJoinStep()');assert.match(doc.getElementById('joinError').textContent,/first name and email/);
 doc.getElementById('joinContact').value='new@example.com';p.eval('nextJoinStep()');assert.match(doc.getElementById('joinError').textContent,/18 or older/);doc.getElementById('joinAgree').checked=true;p.eval('nextJoinStep()');await tick();assert.equal(p.eval('s.joinStep'),'joinCode');doc.getElementById('signinCode').value='000000';await p.eval('signinVerify()');assert.match(doc.getElementById('joinError').textContent,/incorrect/);doc.getElementById('signinCode').value='123456';await p.eval('signinVerify()');assert.equal(p.eval('s.joinStep'),2);await p.eval('openCamera()');assert.match(doc.getElementById('joinError').textContent,/No camera/);p.eval('backToDetails()');assert.equal(doc.getElementById('joinName').value,'New');
 assert.equal(p.eval(`pic('x" onerror="alert(1)')`),'');
 const member=make('sender'),m=member.window;await tick();assert.equal(m.eval('s.view'),'dashboard');assert.equal(qrCreates,0);m.eval('openInvite()');await tick();assert.equal(qrCreates,1);assert.match(m.document.querySelector('.liveQr').src,/data:image\/svg/);assert.match(m.document.querySelector('#qrTimer').textContent,/Ready for/);assert.match(m.document.querySelector('.modal').textContent,/15 minutes.*not a sendable link/);m.eval("inviteMode('send')");assert.match(m.document.querySelector('.modal').textContent,/separate invitation link/);m.document.dispatchEvent(new m.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(m.document.getElementById('modalHost').innerHTML,'');assert.equal(qrCreates,1);
 const prospect=make(null,'https://chempatible.com/?invite='+token),w=prospect.window;await tick();assert.equal(w.eval('s.view'),'invitee');assert.equal(w.eval('connectionRef().token'),token);assert.equal(w.eval('s.member.answers.length'),0);await w.eval('startProspect()');
 for(let i=0;i<5;i++){w.eval('pick(0)');await w.eval('answerQuestion()')}
 assert.equal(w.eval('s.view'),'revealPhoto');assert.match(w.document.body.textContent,/Sign up to save these five answers/);w.eval(`s.prospect.photo='${photo}';render()`);w.document.getElementById('newMemberName').value='Mike';w.document.getElementById('newMemberContact').value='mike@example.com';await w.eval('finishProspectRegistration()');assert.match(w.document.getElementById('revealPhotoError').textContent,/18 or older/);w.document.getElementById('newMemberAgree').checked=true;await w.eval('finishProspectRegistration()');assert.equal(w.eval('s.view'),'results');assert.equal(w.document.querySelectorAll('.revealPeople img').length,2);assert.equal(w.document.querySelectorAll('.revealItem').length,5);assert.match(w.document.body.textContent,/CREATE MY INSTANT VIBE/);
 w.eval('showRequest()');assert.equal(w.document.getElementById('prospectName'),null);assert.equal(w.document.getElementById('prospectContact'),null);assert.equal(w.document.querySelectorAll('.chatPair img').length,2);w.eval('backToFirstResults()');assert.equal(w.eval('s.view'),'results');w.eval('showRequest()');await w.eval('sendRequest()');assert.equal(w.eval('s.modal'),'verifyEmail');w.eval('closeInvite()');assert.equal(state.status,'firstResults');await w.eval('sendRequest()');w.document.getElementById('verifyEmailCode').value='123456';await w.eval('confirmVerify()');assert.equal(state.status,'request');assert.equal(w.eval('s.view'),'dashboard');assert.equal(w.document.querySelector('.inlineChat'),null);assert.match(w.document.querySelector('.connectionFocus').textContent,/Waiting for their answer/);
 await m.eval('refreshLive()');assert.match(m.document.querySelector('.connectionFocus').textContent,/Keep going or pass/);await m.eval('acceptRequest()');assert.equal(state.status,'secondFive');assert.equal(m.document.querySelector('.inlineChat'),null);await w.eval('refreshLive()');assert.match(w.document.querySelector('.connectionFocus').textContent,/Play the next five/);
 // A new browser recovers received connection entirely through authenticated inbox by id.
 const returned=make('receiver'),r=returned.window;await tick();await r.eval('refreshLive()');assert.equal(r.eval('s.actor'),'prospect');assert.equal(r.eval('s.liveToken'),'');assert.equal(r.eval('s.liveId'),id);assert.equal(r.eval('connectionRef().id'),id);assert.equal(r.document.querySelectorAll('.focusPhotos img').length,2);assert.match(r.document.querySelector('.connectionFocus').textContent,/Play the next five/);await r.eval('startSecondFive()');assert.equal(r.eval('s.view'),'questions');assert.match(r.document.querySelector('.question').textContent,/EMOTIONAL EXPRESSION/);r.eval('pick(1)');await r.eval('answerQuestion()');r.eval('goHome()');await r.eval('refreshLive()');await r.eval('startSecondFive()');assert.equal(r.eval('s.prospect.answers.length'),6,'back and resume preserve the partial next five');
 for(let i=0;i<4;i++){r.eval('pick(1)');await r.eval('answerQuestion()')}
 assert.equal(state.status,'secondResults');assert.equal(r.eval('s.view'),'results');assert.equal(r.eval('s.member.answers.length'),10);assert.equal(receiver.answers.length,10);assert.equal(r.eval('s.account.answers.length'),10);r.eval(`s.inbox.push({id:'sent-copy',side:'member',status:'request',prospect_name:'Sam',prospect_photo:'${photo}',prospect_answers:[0,0,0,0,0],messages:[]});selectChempat('sent-copy')`);assert.equal(r.eval('s.actor'),'member');assert.equal(r.eval('s.member.name'),'Mike');assert.equal(r.eval('s.member.answers.length'),10);r.eval(`selectChempat('${id}')`);assert.equal(r.eval('s.actor'),'prospect');assert.equal(r.eval('s.prospect.answers.length'),10);r.eval(`selectLiveConnection('${id}')`);assert.equal(r.eval('s.actor'),'prospect');assert.match(r.document.body.textContent,/ASK TO CHAT/);assert.equal(r.document.querySelector('#message'),null);await m.eval('refreshLive()');assert.equal(m.document.querySelector('.inlineChat'),null);await r.eval('requestChat()');assert.equal(state.status,'chatRequested');assert.match(r.document.body.textContent,/Waiting for their chat decision/);await m.eval('refreshLive()');await m.eval('acceptRequest()');assert.equal(state.status,'chat');await r.eval('refreshLive()');assert.ok(r.document.querySelector('.inlineChat'));assert.ok(m.document.querySelector('.inlineChat'));assert.ok(r.document.querySelector('.chatUpload input'));
 r.document.getElementById('message').value='Hello from my returned page';await r.eval('sendMessage()');assert.equal(lastAction.id,id);assert.match(r.document.querySelector('.inlineChat').textContent,/Hello from my returned page/);await r.eval("reactChat(0,'like')");assert.equal(state.messages[0].reactions.prospect,'like');r.eval('openConversation()');assert.equal(r.document.querySelectorAll('.chatPair img').length,2);r.eval('goHome()');r.eval(`selectChempat('${id}',true)`);assert.equal(r.document.querySelectorAll('.secretCompare').length,10);assert.equal(r.document.querySelector('.inlineChat'),null);r.eval(`selectChempat('${id}')`);assert.ok(r.document.querySelector('.inlineChat'));
 // Existing answers are reused after scanning another invitation; no first-five re-entry.
 state.status='invited';state.prospect_answers=[];const existing=make('receiver','https://chempatible.com/?invite='+token),e=existing.window;await tick();assert.equal(e.eval('s.prospect.answers.length'),10);await e.eval('startProspect()');assert.equal(e.eval('s.view'),'results');assert.equal(e.document.getElementById('newMemberName'),null);assert.equal(state.prospect_answers.length,5);
 // Post reveal creation only asks for the missing five, then creates a code once.
 e.eval('s.prospect.answers=s.prospect.answers.slice(0,5);createMyVibe()');assert.equal(e.eval('s.view'),'questions');assert.match(e.document.querySelector('.question').textContent,/EMOTIONAL EXPRESSION/);const before=qrCreates;for(let i=0;i<5;i++){e.eval('pick(2)');await e.eval('answerQuestion()')}await tick();assert.equal(e.eval('s.prospect.answers.length'),10);assert.equal(qrCreates,before+1);assert.equal(e.eval('s.modal'),'qr');e.eval('closeInvite()');e.eval('createMyVibe()');await tick();assert.equal(e.eval('s.prospect.answers.length'),10);assert.equal(qrCreates,before+2);e.eval('closeInvite()');
 // The original invitee can invite a new person, make two mutual choices, and chat from their outgoing pane.
 e.eval("s.modal='send';renderModal()");e.document.getElementById('inviteName').value='Sam';e.document.getElementById('inviteContact').value='sam@example.com';await e.eval('prepareInvite()');await tick();await e.eval('refreshOutgoing()');assert.equal(e.eval('s.outgoing.length'),1);assert.match(e.document.querySelector('.chempatRail').textContent,/Sam/);
 Object.assign(outgoing,{status:'request',prospect_answers:[0,1,2,0,1]});await e.eval('refreshOutgoing()');e.eval(`selectChempat('${outgoingId}');openOutgoing('${outgoingId}')`);assert.match(e.document.querySelector('.outgoingModal').textContent,/KEEP GOING/);await e.eval("decideOutgoing('accept')");assert.equal(outgoing.status,'secondFive');assert.equal(e.document.getElementById('outgoingMessage'),null);e.eval('closeInvite()');
 Object.assign(outgoing,{status:'secondResults',prospect_answers:[0,1,2,0,1,0,1,2,0,1]});await e.eval('refreshOutgoing()');e.eval(`selectChempat('${outgoingId}',true)`);assert.equal(e.document.querySelectorAll('.secretCompare').length,10);assert.equal(e.document.querySelector('.inlineChat'),null);e.eval('showSecondResults()');assert.equal(e.eval('s.view'),'dashboard');assert.match(e.document.querySelector('.focusHeader').textContent,/Sam/);assert.match(e.document.querySelector('.focusHeader').textContent,/You/);assert.doesNotMatch(e.document.querySelector('.focusHeader').textContent,/Cindy/);assert.doesNotMatch(e.document.querySelector('.focusHeader').textContent,/ASK TO CHAT/);assert.equal(e.eval('s.member.name'),'Cindy','outgoing reveal must preserve original received pair');
 outgoing.status='chatRequested';await e.eval('refreshOutgoing()');e.eval(`selectChempat('${outgoingId}')`);await e.eval("decideOutgoing('accept')");assert.equal(outgoing.status,'chat');e.document.getElementById('outgoingMessage').value='Hey Sam';await e.eval('sendOutgoingMessage()');assert.match(e.document.querySelector('.inlineChat').textContent,/Hey Sam/);await e.eval("reactChat(0,'like')");assert.equal(outgoing.messages[0].reactions.member,'like');
 await e.eval("sendChatPhoto({target:{files:[{type:'text/plain'}]}})");assert.match(e.document.getElementById('chatError').textContent,/Choose an image/);
 e.eval(`URL.createObjectURL=()=>'/local-photo';URL.revokeObjectURL=()=>{};Image=class{width=320;height=320;set src(v){this.onload()}};HTMLCanvasElement.prototype.getContext=()=>({drawImage(){}});HTMLCanvasElement.prototype.toDataURL=()=>'${photo}'`);await e.eval("sendChatPhoto({target:{files:[{type:'image/jpeg'}]}})");assert.equal(outgoing.messages.at(-1).photo,photo);assert.ok(e.document.querySelector('.chatPhoto'));
 // A failed verified email send offers retry without asking for another code.
 m.eval("pendingInvite={name:'Sam',email:'sam@example.com'};renderVerify();emailApi=async(data)=>{if(data.action==='verify')return {ok:true};throw Error('Temporary send failure')}");m.document.getElementById('emailCode').value='123456';await m.eval('verifyAndSend()');assert.equal(m.document.getElementById('emailCode').disabled,true);assert.match(m.document.querySelector('.modalForm button').textContent,/RETRY SEND/);assert.match(m.document.getElementById('verifyError').textContent,/Temporary send failure/);m.eval('closeInvite()');
 // Safety and cancellation stay available; legacy chat retains composer.
 state.status='chat';await m.eval('refreshLive()');m.eval(`selectChempat('${id}');openEnd('${id}','unmatch')`);m.eval('closeInvite()');assert.equal(state.status,'chat');m.eval(`openEnd('${id}','report')`);await m.eval('confirmEnd()');assert.match(m.document.getElementById('endError').textContent,/Choose what happened/);m.document.querySelector('input[value=harassment]').checked=true;m.document.getElementById('reportNote').value='Unwanted contact';await m.eval('confirmEnd()');assert.equal(state.status,'ended');assert.equal(m.document.querySelector('.inlineChat'),null);
 r.eval('confirmLogout()');r.eval('closeInvite()');assert.equal(r.eval('s.view'),'dashboard');r.eval('confirmLogout()');await r.eval('logout()');assert.equal(r.eval('s.view'),'landing');assert.ok(r.document.querySelector('.publicHero'));r.eval('showSignin()');r.document.getElementById('signinEmail').value='mike@example.com';await r.eval('signinStart()');r.document.getElementById('signinCode').value='123456';await r.eval('signinVerify()');await tick();assert.equal(r.eval('s.view'),'dashboard');assert.equal(r.eval('s.liveToken'),'');assert.match(r.document.body.textContent,/Connection ended/);
 console.log('Two-browser UI passed: public opening, signup, mutual stages, verified reentry, existing-answer reuse, chat, safety, and cancellation');
}finally{for(const p of pages)p.window.close()}
