import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import test from 'node:test';
const html=readFileSync(new URL('../wild-hub/index.html',import.meta.url),'utf8');
const source=readFileSync(new URL('../wild-hub/wild-hub.js',import.meta.url),'utf8');
function fixture(hash='home'){
 const dom=new JSDOM(html,{url:`https://example.test/#${hash}`,runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,d=w.document;
 w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 w.fetch=()=>{throw Error('Network is prohibited')};w.eval(source+'\nwindow.__test={render,action};');
 const click=(action,id)=>{const el=d.querySelector(`[data-action="${action}"]${id?`[data-id="${id}"]`:''}`);assert.ok(el,`action ${action}`);el.click()};
 const route=hash=>{w.location.hash=hash;w.__test.render()};
 const submit=id=>d.querySelector(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 return {w,d,click,route,submit,close:()=>w.close()};
}
function request(f){f.route('host');f.click('request');f.click('fill-sample');f.d.querySelector('#request-agree').checked=true;f.submit('#request-form');f.click('close')}
test('landing has the approved promise and excludes relationship/game content',()=>{const f=fixture();try{assert.match(f.d.querySelector('h1').textContent,/Your privatenetwork/);assert.match(f.d.body.textContent,/Open to requests. Yours to approve./);assert.doesNotMatch(f.d.querySelector('main').textContent,/compatibility|dating|reward|secret|vibe/i);assert.match(f.d.body.textContent,/DESIGN PREVIEW/)}finally{f.close()}});
test('direct member view is visually closed until a simulated host approval',()=>{const f=fixture('circle');try{assert.match(f.d.querySelector('main').textContent,/This door opens with approval/);request(f);f.route('circle');assert.match(f.d.querySelector('main').textContent,/This door opens with approval/);f.route('dashboard');f.click('approve','visitor');f.route('circle');assert.match(f.d.querySelector('main').textContent,/Welcome to the little corner/);assert.match(f.d.querySelector('main').textContent,/not a secure private space/);assert.doesNotMatch(f.d.querySelector('main').textContent,/@example.com/)}finally{f.close()}});
test('request form validates fields, photo and demo acknowledgement without side effects',()=>{const f=fixture('host');try{f.click('request');f.submit('#request-form');assert.match(f.d.querySelector('#request-error').textContent,/name/);f.click('fill-sample');f.submit('#request-form');assert.match(f.d.querySelector('#request-error').textContent,/acknowledge/);f.d.querySelector('#request-agree').checked=true;f.submit('#request-form');assert.match(f.d.querySelector('#dialog-content').textContent,/Nothing has been sent/);assert.equal(f.w.localStorage.length,0);assert.equal(f.w.sessionStorage.length,0);assert.equal(f.d.cookie,'')}finally{f.close()}});
test('Pass never opens the member view and repeat decisions are idempotent',()=>{const f=fixture('host');try{request(f);f.route('dashboard');f.click('pass','visitor');f.w.__test.action('approve','visitor');f.route('host');assert.match(f.d.querySelector('main').textContent,/passed on/);f.route('circle');assert.match(f.d.querySelector('main').textContent,/This door opens with approval/)}finally{f.close()}});
test('withdraw, leave and reset remove sample access',()=>{const f=fixture();try{request(f);f.click('withdraw');assert.ok(f.d.querySelector('[data-action="request"]'));request(f);f.route('dashboard');f.click('approve','visitor');f.route('circle');f.click('leave');f.route('circle');assert.match(f.d.querySelector('main').textContent,/This door opens with approval/);f.route('dashboard');f.click('reset');assert.equal(f.d.querySelectorAll('.request-card').length,3)}finally{f.close()}});
test('sample invitation validates input, escapes values and never creates a link',()=>{const f=fixture('dashboard');try{f.click('invite');f.submit('#invite-form');assert.match(f.d.querySelector('#invite-error').textContent,/valid email/);f.d.querySelector('#invite-name').value='<img src=x onerror=alert(1)>';f.d.querySelector('#invite-email').value='sample@example.com';f.submit('#invite-form');assert.match(f.d.querySelector('#dialog-content').textContent,/EMAIL PREVIEW · NOT SENT/);assert.equal(f.d.querySelectorAll('#dialog-content img').length,0);assert.equal(f.d.querySelectorAll('#dialog-content a').length,0)}finally{f.close()}});
test('request content is escaped when rendered in host view',()=>{const f=fixture('host');try{f.click('request');f.click('fill-sample');f.d.querySelector('#request-name').value='<script>alert(1)</script>';f.d.querySelector('#request-intro').value='<img src=x onerror=alert(1)>';f.d.querySelector('#request-agree').checked=true;f.submit('#request-form');f.click('close');f.route('dashboard');assert.equal(f.d.querySelectorAll('main script').length,0);assert.equal(f.d.querySelectorAll('main img[onerror]').length,0);assert.match(f.d.querySelector('main').textContent,/<img src=x onerror=alert\(1\)>/)}finally{f.close()}});
test('dialog close and escape restore focus; navigation dismisses the modal',async()=>{const f=fixture('host');try{const trigger=f.d.querySelector('[data-action="request"]');trigger.focus();f.click('request');f.d.querySelector('#dialog').dispatchEvent(new f.w.Event('cancel',{cancelable:true}));assert.equal(f.d.querySelector('#dialog').open,false);assert.equal(f.d.activeElement,trigger);assert.equal(f.d.body.style.overflow,'');f.click('request');f.route('dashboard');await new Promise(resolve=>setTimeout(resolve,10));assert.equal(f.d.querySelector('#dialog').open,false)}finally{f.close()}});
test('membership and one-time support selections are explicit non-payment demos',()=>{const f=fixture('host');try{f.click('support');assert.match(f.d.querySelector('#dialog-content').textContent,/Illustrative amounts/);f.click('preview-monthly');assert.match(f.d.querySelector('#dialog-content').textContent,/No subscription, payment, or membership was created/);f.click('support-back');f.click('preview-annual');assert.match(f.d.querySelector('#dialog-content').textContent,/\$10\/year/);f.click('support-back');f.click('preview-support','5');assert.match(f.d.querySelector('#dialog-content').textContent,/one-time \$5/);assert.equal(f.d.querySelectorAll('input').length,0)}finally{f.close()}});
test('no runtime network, persistence, tracking or third-party assets; restrictive CSP and noindex',()=>{assert.doesNotMatch(source,/\bfetch\s*\(|XMLHttpRequest|WebSocket|sendBeacon|localStorage|sessionStorage|document\.cookie|serviceWorker|https?:\/\//);assert.match(html,/connect-src 'none'/);assert.match(html,/form-action 'none'/);assert.match(html,/noindex, nofollow, noarchive/);assert.doesNotMatch(html,/https?:\/\//)});
test('responsive rules retain single-column mobile layouts, input size and touch targets',()=>{const f=fixture();try{const style=f.d.createElement('style');style.textContent=readFileSync(new URL('../wild-hub/wild-hub.css',import.meta.url),'utf8');f.d.head.append(style);const rules=[...style.sheet.cssRules];style.remove();const atWidth=(items,width)=>items.map(rule=>{if(rule.type!==f.w.CSSRule.MEDIA_RULE)return rule.cssText;if(rule.conditionText.includes('prefers-reduced-motion'))return '';const match=rule.conditionText.match(/^\((min|max)-width:\s*(\d+)px\)$/);assert.ok(match,rule.conditionText);return (match[1]==='min'?width>=+match[2]:width<=+match[2])?atWidth([...rule.cssRules],width):''}).join('\n');for(const width of [320,375,390,430,760,1024,1440]){const viewportStyle=f.d.createElement('style');viewportStyle.textContent=atWidth(rules,width);f.d.head.append(viewportStyle);f.route('home');assert.equal(f.w.getComputedStyle(f.d.querySelector('.hero')).display,width<=760?'block':'grid',`${width}: hero`);assert.equal(f.w.getComputedStyle(f.d.querySelector('.steps')).gridTemplateColumns,width<=760?'1fr':'repeat(3,1fr)',`${width}: steps`);assert.ok(parseFloat(f.w.getComputedStyle(f.d.querySelector('.button')).minHeight)>=44);f.route('host');f.click('request');assert.equal(f.w.getComputedStyle(f.d.querySelector('#request-email')).fontSize,'16px');assert.equal(f.w.getComputedStyle(f.d.querySelector('.close')).width,'44px');f.click('close');f.route('dashboard');assert.equal(f.w.getComputedStyle(f.d.querySelector('.request-list')).gridTemplateColumns,width<=760?'1fr':width<=1050?'repeat(2,1fr)':'repeat(3,1fr)');viewportStyle.remove()}}finally{f.close()}});
